### ISSUE TITLE
New homepage

### ISSUE THREAD

**Issue by lgbaldoni** [cmdrkotori/mpc-qt-origin#1]
First of all, I'm very glad you've come back. I hope you're in good health.

A while ago I created https://gitlab.com/mpc-qt to keep a backup of your old repository, but since I don't actually use it, perhaps you'd prefer having it instead?

**Comment by eao** [comment]
Also glad to see you back.  Hope you are OK.

**Comment by cmdrkotori** [comment]
> A while ago I created https://gitlab.com/mpc-qt to keep a backup of your old repository, but since I don't actually use it, perhaps you'd prefer having it instead?

To be honest, I tried gitlab once but the gui seemed a bit of a mess. I'll pass this time. Thanks though.

**Comment by cmdrkotori** [comment]
Should have closed this ages ago.
