### ISSUE TITLE
Build fails with Qt 5.12.7

### ISSUE THREAD

**Issue by lgbaldoni** [cmdrkotori/mpc-qt-origin#2]
I know it's not bleeding edge, but many distributions prefer LTS.

Using openSUSE Leap 15.2 with gcc 9.
Here's the [log](https://github.com/cmdrkotori/mpc-qt-origin/files/4868934/mpc-qt-20200621.txt).

**Comment by cmdrkotori** [comment]
Ok, just needed to roll back some things from c589b2ff9f73b6ecd2f417d4b183a0dac8e8cca8.

Fixed in 0fae011e7b21efc3c54b91bac616f4327c4d49e0.

**Comment by lgbaldoni** [comment]
Looks like we aren't done [yet](https://github.com/cmdrkotori/mpc-qt-origin/files/4870659/mpc-qt-qt512_2.txt).

**Comment by cmdrkotori** [comment]
Fixed in 043d6764511742843183feb5fe77658776d648f2. Please let me know if there's anything else.

**Comment by cmdrkotori** [comment]
Better make that d2c005540d5f776a86d449f15d7b215c3175877d, sorry.

**Comment by lgbaldoni** [comment]
That did the trick, TYVM.
