### ISSUE TITLE
Playlist subwindow remains open at restart

### ISSUE THREAD

**Issue by lgbaldoni** [cmdrkotori/mpc-qt-origin#3]
Even if empty, no matter the settings. This has started happening since upgrading to Qt 5.12.
Old snapshot from last year shows the same problem as current master.

If I delete the configuration folder sometimes it goes and sometimes it doesn't (!).

I'm about at the end of my rope here😱

**Comment by lgbaldoni** [comment]
I must also add that the problem is intermittent. Is there anything I should try/test, should I encounter it again?

**Comment by mfsoup** [comment]
Same problem here on a Windows build.

**Comment by lgbaldoni** [comment]
On the other hand, I haven't seen it since!

**Comment by cmdrkotori** [comment]
I haven't seen this. Perhaps it's got to do with the way the playlist window state is tracked.

> Same problem here on a Windows build.

fyi, the windows build is a bit old. The source code is waiting on a patchset for the half-complete playlist undeleter and then I may get to making a release.

**Comment by mfsoup** [comment]
> 
> 
> I haven't seen this. Perhaps it's got to do with the way the playlist window state is tracked.
> 
> > Same problem here on a Windows build.
> 
> fyi, the windows build is a bit old. The source code is waiting on a patchset for the half-complete playlist undeleter and then I may get to making a release.

Oh, it's actually a recently compiled Windows build. I didn't have this problem on the old 18.08 build.

![image](https://user-images.githubusercontent.com/38110452/88111307-b10c2300-cb7b-11ea-95e5-a58af19e2f84.png)

**Comment by cmdrkotori** [comment]
> Oh, it's actually a recently compiled Windows build.

Impressive.

>I didn't have this problem on the old 18.08 build.

Hmm, that's funny. Either it's a Qt toolkit regression or I changed the way the toggle code works. I'm running Qt 5.15 as well and it doesn't occur with me. :thinking: 

> I must also add that the problem is intermittent. Is there anything I should try/test, should I encounter it again?

Yes, check if the toggle box on the menu matches the state of the playlist's visibility. Try toggling it through the menu.

**Comment by mfsoup** [comment]
> Yes, check if the toggle box on the menu matches the state of the playlist's visibility. Try toggling it through the menu.

My menu toggle always matches the visibility of the playlist window. Toggling it off from the menu and reopening the video just causes it to come back.

**Comment by lgbaldoni** [comment]
> My menu toggle always matches the visibility of the playlist window. Toggling it off from the menu and reopening the video just causes it to come back.

I haven't seen it recently, but that would be my recollection as well.

**Comment by mfsoup** [comment]
I probably should've tried this earlier but deleting my config folder seemed to have fixed it. 

After some more testing, it seems like it's caused by having an old settings.json file. I can upload it if you'd like.

**Comment by cmdrkotori** [comment]
Ok. Next time this happens, the solution is probably to delete geometry.json.
