### ISSUE TITLE
Create an AppImage for mpc-qt

### ISSUE THREAD

**Issue by SmootheSmooth** [cmdrkotori/mpc-qt-origin#4]
Hello,

can you create an AppImage for mpc-qt? Then it runs on almost all Linux distributions.

Here is more information, what is AppImage?
https://appimage.org/

**Comment by cmdrkotori** [comment]
The linuxdeploy tool on my machine errors out on libpulsecommon-13.99.so.

If compiling is difficult for you, I believe you can run the windows version on wine.

**Comment by j75fsd48g** [comment]
> The linuxdeploy tool on my machine errors out on libpulsecommon-13.99.so.

Hello can you help?
@probonopd @TheAssassin

**Comment by TheAssassin** [comment]
Please file issues on the corresponding bug trackers. We can't provide support for our tools in any random spot.

**Comment by probonopd** [comment]
For `linuxdeploy`, this would be https://github.com/linuxdeploy/linuxdeploy/issues.

Do you get the same result when using https://github.com/probonopd/go-appimage/tree/master/src/appimagetool#appimagetool?

**Comment by cmdrkotori** [comment]
I'll be closing this because on Linux we only support compiling. If someone really wants this, they can make a PR with a file called `make-release-linux.sh`. If you don't know how to compile this, install Arch or BSD which actually have packages of this program.
