### ISSUE TITLE
Request: Support for user scripts

### ISSUE THREAD

**Issue by Aurareus** [cmdrkotori/mpc-qt-origin#5]
As a long time user of MPC-BE who has recently switched to Linux I am extremely thankful for MPC-QT as I really don't enjoy using mpv without a frontend.
There are some [user scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts) and Vapoursynth filters (like [SVP](https://www.svp-team.com/)) that I'd really like to use though, so I was wondering whether it would be possible to support this?

I realize this is probably a bit of a tall order since (afaik) libmpv doesn't allow for the use of scripts.

**Comment by cmdrkotori** [comment]
We already have support for user scripts. Place them under a "scripts" folder inside the mpc-qt config folder. It should be under AppData/Roaming.
However we lack any real way of interacting with the scripts, so no keyboard input.

**Comment by Aurareus** [comment]
Sorry, I had no idea user scripts were already supported.
Where can I find the equivalent directory on Linux?

EDIT: Have tried putting scripts in ~/.config/mpc-qt/scripts/
but they don't seem to be working for me.

EDIT: Got scripts loading.
Could you let me know where the `script-opts` directory should be?

EDIT: Ended up just hard coding the settings I needed into the script.
All good now =)
