### ISSUE TITLE
Support mounts created by udisks on Unix/Linux

### ISSUE THREAD

**Issue by tuaris** [cmdrkotori/mpc-qt-origin#6]
Users of MATE desktop (and possibly GNOME an KDE) are not able to open files from mounts points setup by [udisks](https://www.freedesktop.org/wiki/Software/udisks/). After a quick search on Github, I found a possible Qt library that might help with that https://github.com/udisks-qt/udisks-qt.

**Comment by cmdrkotori** [comment]
Works on my machine.
Are you sure you've got all your group memberships? My groups are `disk wheel kvm video audio optical floppy storage scanner input vboxusers libvirt `.

**Comment by cmdrkotori** [comment]
Not reproducible.
