### ISSUE TITLE
HDR videos black screen in MPC-QT, but play fine in mpv player and other players (SDR system)

### ISSUE THREAD

**Issue by BillFleming** [cmdrkotori/mpc-qt-origin#7]
Is there a specific trick or settings combination to getting HDR videos to work on a typical linux PC configuration (non-HDR monitor)?
Or are HDR videos just not properly supported yet in MPC-QT?

Some example test videos to see the problem:
http://download.opencontent.netflix.com.s3.amazonaws.com/TechblogAssets/Meridian/encodes/Meridian_3840x2160_5994fps_SDR.mp4 < plays fine as expected
http://download.opencontent.netflix.com.s3.amazonaws.com/TechblogAssets/Meridian/encodes/Meridian_3840x2160_5994fps_HDR10.mp4 <- black screen, but plays fine in other linux players
http://download.opencontent.netflix.com.s3.amazonaws.com/TechblogAssets/Meridian/encodes/Meridian_3840x2160_5994fps_DolbyVision.mp4 < Actually shows a picture but colors are messed up (that is a whole separate mess that MPV has to solve)

I have multiple ARCH machines all with AMD GPUs and cinnamon desktop and so far MPC-QT has black screens with HDR on all of them.

I actually do have some monitors (using lcd controller boards from ebay, etc) that might have proper HDR programming in them to test actual HDR playback, so I could do some testing with those with some direction. This one LCD next to me, when I turn HDR on (instead of auto) it just goes to a white screen so I may need to setup a specific system to use it to test out a possible HDR mode switch in MPC-QT on it.

**Comment by cmdrkotori** [comment]
Turn off HDR Compute Peak

![Screenshot_20210321_183845](https://user-images.githubusercontent.com/65291121/111898915-bc9a4b80-8a74-11eb-8ef6-150ef764ca7c.png)
